version: '3.3'
services:
  www:
    image: php:apache
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:latest
    container_name: db
    volumes:
      - "./db:/docker-entrypoint-initdb.d" 
    environment:
      - MYSQL_DATABASE=eatsnow
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
